name: CI
on: [push]
jobs:
  container:
    runs-on: ubuntu-latest
    container: frekele/ant:1.10.3-jdk8
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run in container
        run: |
          find / -name "rt.jar"

        